project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/slides.html
        text: Slides
      - href: about.html
        text: About
      - about.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true



